Move the testbed federation config to the production repositories
osism/defaults pull request #147
Opened 2023-09-14 08:32 UTC by JuanPTM

Part of https://github.com/SovereignCloudStack/issues/issues/412

2023-09-14 09:46 UTC, berendt requested changes

2023-09-14 09:46 UTC, berendt commented on all/099-kolla.yml
> +enable_keystone_federation: "no"        # NOTE: Not enabled by default
Comment can be removed.

2023-09-14 09:46 UTC, berendt commented on all/099-kolla.yml
> +keystone_enable_federation_openid: "no"  # NOTE: Not enabled by default
Comment can break removed.

2023-09-14 09:46 UTC, berendt commented on all/099-kolla.yml
>  keystone_federation_oidc_response_type: "code"   # NOTE: use authorization code in keystone instead of default upstream
Add this comment above the parameter.

2023-09-14 10:01 UTC, JuanPTM commented
Removed comments and moved the other one on  top of the parameter

2023-09-15 06:03 UTC, berendt approved these changes

2023-09-15 06:03 UTC, merged